// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "@/components/ui/Navbar";
// // import Footer from "@/components/ui/Footer";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         <Navbar />
// //         {children}
// //         <Footer />
// //       </body>
// //     </html>
// //   );
// // }

// import './globals.css';
// import { config } from '@/lib/config';
// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';
// import { Inter, Poppins } from 'next/font/google';
// import WhatsAppButton from '@/components/WhatsAppButton';

// const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '700'] });
// const poppins = Poppins({ subsets: ['latin'], weight: ['600', '700'] });

// export const metadata = {
//   title: config.meta.title,
//   description: config.meta.description,
//   openGraph: {
//     title: config.meta.title,
//     description: config.meta.description,
//     images: [config.meta.ogImage],
//   },
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="pt-BR">
//       <head>
//         <link rel="icon" href={config.favicon} />
//       </head>
//       <body className={`${inter.className} ${poppins.className} font-body text-body bg-[#FAF5EA]`}>
//         <Navbar />
//         {children}
//         <WhatsAppButton />
//         <Footer />
//       </body>
//     </html>
//   );
// }
import './globals.css';
import { config } from '@/lib/config';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Inter, Poppins } from 'next/font/google';
import WhatsAppButton from '@/components/WhatsAppButton';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-inter',
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: config.meta.title,
  description: config.meta.description,
  metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'),
  openGraph: {
    title: config.meta.title,
    description: config.meta.description,
    images: [{ url: config.meta.ogImage, width: 1200, height: 630 }],
    url: '/',
    type: 'website',
    locale: 'pt_BR',
  },
  twitter: {
    card: 'summary_large_image',
    title: config.meta.title,
    description: config.meta.description,
    images: [config.meta.ogImage],
  },
  icons: {
    icon: config.favicon,
  },
  keywords: ['moda feminina', 'moda masculina', 'acessórios', 'loja virtual', 'Lojas Loula'],
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} ${poppins.variable} bg-[#FAF5EA] text-body font-inter min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className="flex-grow">{children}</main>
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}